# Generated by Django 5.1.1 on 2024-10-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagepload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepload',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
